# Generated by Django 5.0.4 on 2024-06-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_documents_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='page_content',
            field=models.TextField(default=''),
        ),
    ]
