# Generated by Django 5.0.4 on 2024-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_documents_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbots',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
